[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template]
  incoming-hooks = ["WixData"]

[template.environment]
  NEXT_PUBLIC_WIX_CLIENT_ID = "Wix Headless Client ID"
